2025-03-11 10:12:34,640 - nisto - INFO - Starting Network Topology Designer
2025-03-11 10:12:35,067 - nisto - ERROR - Unhandled exception in main
Traceback (most recent call last):
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/main.py", line 63, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/main.py", line 54, in main
    main_window = MainWindow()
                  ^^^^^^^^^^^^
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/controllers/main_window.py", line 63, in __init__
    self.file_manager = FileManager(
                        ^^^^^^^^^^^^
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/controllers/file_manager.py", line 19, in __init__
    self.dialog_manager = FileDialogManager(main_window.view)
                                            ^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'view'
